name: sail_test
description: A Flutter app for MES Department, BSP.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.5 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  image: ^4.0.17
  fluttertoast: ^8.0.8
  flutter_riverpod: ^2.1.3
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.18.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.9
  animations: ^2.0.7
  flutter_barcode_scanner: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600