name: sail_test
description: A Flutter app for MES Department, BSP.
version: 1.0.0+1
environment: 
  sdk: ">=2.19.2 <3.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  image: ^3.0.2
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.0.8
  flutter_riverpod: ^2.1.3
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.18.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.9
  camera: ^0.10.5+2
  animations: ^2.0.7
  flutter_barcode_scanner: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600